name: release

on:
  push:

jobs:
  run-tests:
    name: Run test cases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [^1]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Ubuntu Build
        if: matrix.os == "ubuntu-latest"
        run: |
          CGO_ENABLED=0 go build -o consul-template-${{ matrix.os }}

      - name: Windows and MacOS Build
        if: matrix.os != "ubuntu-latest"
        run: |
          go build -o consul-template-${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: consul-template-${{ matrix.os }}
